name: CI Workflow

on: 
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'

jobs:
  # Job 1: Checkov Security Scan
  checkov:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          
      - name: Run Checkov Security Scan
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: exercise1/Terraform
          framework: terraform
          soft-fail-threshold: Critical
  
  # Job 2: Terraform apply
  terraform-apply:
    runs-on: ubuntu-22.04
    environment: AWS
    needs: checkov
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Initialize Terraform
        working-directory: exercise1/Terraform
        run: terraform init
      
      - name: Validate Terraform
        working-directory: exercise1/Terraform
        run: terraform validate

      - name: Plan Terraform changes
        working-directory: exercise1/Terraform
        run: terraform plan -out=tfplan
        
      - name: Apply Terraform
        working-directory: exercise1/Terraform
        run: terraform apply -auto-approve

      - name: Clean up
        working-directory: exercise1/Terraform
        run: rm tfplan
  
  # Job 3: Terraform destroy    
  terraform-destroy:
    runs-on: ubuntu-22.04
    environment: AWS
    needs: terraform-apply
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Initialize Terraform
        working-directory: exercise1/Terraform
        run: terraform init

      - name: Destroy Terraform resources
        working-directory: exercise1/Terraform
        run: terraform destroy -auto-approve
