name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  # Job 1: Checkov Security Scan
  checkov:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          
      - name: Run Checkov Security Scan
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: exercise1  # Specify the directory where your code is located
          framework: terraform
# Job 2: Terraform Initialization and Plan
  terraform:
    runs-on: ubuntu-22.04
    environment: AWS
    needs: checkov  # run Terraform only job checkov successfully completes
    steps:
      - uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Initialize Terraform
        working-directory: exercise1
        run: terraform init

      - name: Plan Terraform changes
        working-directory: exercise1
        run: terraform plan -out=tfplan
      
      - name: Validate Terraform changes
        working-directory: exercise1
        run: terraform validate
        
      - name: apply Terraform changes
        working-directory: exercise1
        run: terraform apply -auto-approve

      - name: destroy Terraform changes
        working-directory: exercise1
        run: terraform destroy -auto-approve

      - name: Clean up
        working-directory: exercise1
        run: rm tfplan