name: CI Workflow

on: 
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-22.04
    environment: AWS
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Initialize Terraform
        working-directory: exercise1/terraform
        run: terraform init
      
      - name: Validate Terraform validate
        working-directory: exercise1/terraform
        run: terraform validate

      # - name: Plan Terraform changes
      #   working-directory: exercise1/terraform
      #   run: terraform plan -out=tfplan
        
      # - name: apply Terraform apply
      #   working-directory: exercise1/terraform
      #   run: terraform apply -auto-approve

      # - name: Clean up
      #   working-directory: exercise1/terraform
      #   run: rm tfplan

      - name: destroy Terraform destroy
        working-directory: exercise1/terraform
        run: terraform destroy -auto-approve